import Head from 'next/head'
import { useContext } from 'react'

import BandAdd from '../components/BandAdd'
import BandChart from '../components/BandChart'
import BandList from '../components/BandList'
import { SocketContext } from '../context/SocketContext'

export default function Home () {
  const { online } = useContext(SocketContext)

  return (
    <div>
      <Head>
        <title>Band Names</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container'>
        <div className='alert'>
          <p>Service Status:
            {
              online ? <span className='text-success'> Online</span> : <span className='text-danger'> Ofline</span>
            }
          </p>
        </div>

        <h1>BandNames</h1>
        <hr />

        <div className='row'>
          <div className='col-6'>
            <BandChart />
          </div>
        </div>

        <div className='row'>
          <div className='col-8'>
            <BandList />
          </div>
          <div className='col-4'>
            <BandAdd />
          </div>
        </div>

      </div>

    </div>
  )
}
